version: '3.4'

networks:
  backend:
    driver: bridge

services:
   langara-api:
    container_name: langaraapi
    ports:
      - '5000:5000'
    build: .
    #image: "ghcr.io/highfire1/langaracoursewatcher:latest"
    networks:
      - backend
    volumes:
      - .database:/database

volumes:
  course_watcher_db: